services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shipping_be
    ports:
      - '${PORT:-3333}:3333'
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    networks:
      - shipping_app_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root}
      - MYSQL_USER=${DB_USER:-user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_DATABASE=${DB_DATABASE:-shipping}
    ports:
      - '${DB_PORT:-3306}:3306'
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - shipping_app_network

volumes:
  db_data:

networks:
  shipping_app_network: